# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0

- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'validate'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'AzuretoDevops'
    runAzLogin: true
    commandOptions: '-var-file=dev.auto.tfvars'
    allowTelemetryCollection: true
